
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Keith
 */
public class Librarian extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    GridBagLayout layout = new GridBagLayout();
    BookRequest br;
    ChangePassword1 cp;
    EditProfile ep;
    ManageBook mb;
    ManageBorrower mng;
    ManageStudent ms;
    
    Report r;
    SearchBook sb;
    SoftBook s;
    UploadBook ub;
    ViewBook vb;
    NoticeBoard nb;
    ListOfBooks lob;

    /**
     * Creates new form Librarian
     */
    public Librarian() {
        initComponents();
        
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, yyyy");
        date.setText(sdf.format(d));
        
        
        //show time
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                time.setText(sdf.format(d));
            }
        }).start();
        
        String query = "SELECT anademyName,logo  FROM academy";
        try{
            con = Connectionz.getConnection();
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            if(rs.next()){
                name.setText(rs.getString("anademyName"));
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(rs.getBytes("logo")).getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH));
                logo.setIcon(imageIcon);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
        br = new BookRequest();
        cp = new ChangePassword1();
        ep = new EditProfile();
        mb = new ManageBook();
        mng = new ManageBorrower();
        ms = new ManageStudent();
        
        r = new Report();
        sb = new SearchBook();
        s = new SoftBook();
        ub = new UploadBook();
        vb = new ViewBook();
        nb= new NoticeBoard();
        lob = new ListOfBooks();

        
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(br, c);
        DynamicPanel.add(cp, c);
        DynamicPanel.add(ep, c);
        DynamicPanel.add(mb, c);
        DynamicPanel.add(mng, c);
        DynamicPanel.add(ms, c);
        DynamicPanel.add(r, c);
        DynamicPanel.add(sb, c);
        DynamicPanel.add(s, c);
        DynamicPanel.add(ub, c);
        DynamicPanel.add(vb, c);
        DynamicPanel.add(nb, c);
        DynamicPanel.add(lob, c);
        
        dynamicPanel.setVisible(true);
        nb.setVisible(false);
        ms.setVisible(false);
        mb.setVisible(false);
        lob.setVisible(false);
        mng.setVisible(false);
        br.setVisible(false);
        r.setVisible(false);
        ub.setVisible(false);
        s.setVisible(false);
        sb.setVisible(false);
        ep.setVisible(false);
        cp.setVisible(false);
        
        
    }
    
    /*public Librarian(String username ){
        initComponents();
        uname.setText("User: " +username);
        
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        manageStudent = new javax.swing.JButton();
        manageBook = new javax.swing.JButton();
        searchBook = new javax.swing.JButton();
        viewBook = new javax.swing.JButton();
        uploadBook = new javax.swing.JButton();
        softBook = new javax.swing.JButton();
        report = new javax.swing.JButton();
        bookRequest = new javax.swing.JButton();
        changePass = new javax.swing.JButton();
        editProfile = new javax.swing.JButton();
        noticeBoard = new javax.swing.JButton();
        books = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();
        dynamicPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Librarian Panel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 440, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DEMO VERSION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 190, -1));

        uname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1380, 80));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 153, 51));
        home.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel2.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 50, 100, 50));

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Log Out");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 50, -1, 50));

        name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 29, 250, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("For Community Transformation");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 90));

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("jLabel11");
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 54, 190, 30));

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("jLabel11");
        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 70, 1380, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        jLabel8.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Options");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        manageStudent.setText("Manage Student");
        manageStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentActionPerformed(evt);
            }
        });

        manageBook.setText("Manage Book");
        manageBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBookActionPerformed(evt);
            }
        });

        searchBook.setText("Search Book");
        searchBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookActionPerformed(evt);
            }
        });

        viewBook.setText("Manage Borrower");
        viewBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookActionPerformed(evt);
            }
        });

        uploadBook.setText("Upload Book");
        uploadBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBookActionPerformed(evt);
            }
        });

        softBook.setText("Soft Book");
        softBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        softBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softBookActionPerformed(evt);
            }
        });

        report.setText("Report");
        report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        bookRequest.setText("Book Request");
        bookRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRequestActionPerformed(evt);
            }
        });

        changePass.setText("Change Password");
        changePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassActionPerformed(evt);
            }
        });

        editProfile.setText("Edit Profile");
        editProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileActionPerformed(evt);
            }
        });

        noticeBoard.setText("Notice Board");
        noticeBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noticeBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticeBoardActionPerformed(evt);
            }
        });

        books.setText("List of Books");
        books.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(manageStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addComponent(manageBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(viewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(softBook, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadBook, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(books, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noticeBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePass, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageBook, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(softBook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uploadBook, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(books, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(noticeBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changePass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 23, -1, -1));

        DynamicPanel.setBackground(new java.awt.Color(255, 255, 255));

        dynamicPanel.setBackground(new java.awt.Color(255, 255, 255));
        dynamicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 4));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("No new notifications");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 20));

        dynamicPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 430, 180));

        jPanel7.setBackground(new java.awt.Color(0, 102, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Notifications");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        dynamicPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 170, 60));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DynamicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
                .addContainerGap())
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DynamicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 23, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 174, 1380, 700));

        jPanel5.setBackground(new java.awt.Color(51, 102, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Developed by Keith Tumusiime - +256781363816");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Library Management System | version 1.0 ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel9)
                .addGap(252, 252, 252)
                .addComponent(jLabel10)
                .addContainerGap(521, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 876, 1380, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        jLabel1.setText("Librarian Panel");
        br.setVisible(false);
        cp.setVisible(false);
        ep.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        ms.setVisible(false);
        lob.setVisible(false);
        
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(false);
        ub.setVisible(false);
        dynamicPanel.setVisible(true);
        vb.setVisible(false);
        nb.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void manageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentActionPerformed
        jLabel1.setText("Manage Students");
        br.setVisible(false);
        cp.setVisible(false);
        ep.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        ms.setVisible(true);
        
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(false);
        ub.setVisible(false);
        dynamicPanel.setVisible(false);
        nb.setVisible(false);
    }//GEN-LAST:event_manageStudentActionPerformed

    private void manageBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBookActionPerformed
        jLabel1.setText("Book Collection");
        br.setVisible(false);
        cp.setVisible(false);
        lob.setVisible(false);
        ep.setVisible(false);
        mb.setVisible(true);
        mng.setVisible(false);
        ms.setVisible(false);
        
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(false);
        ub.setVisible(false);
        dynamicPanel.setVisible(false);
        vb.setVisible(false);
    }//GEN-LAST:event_manageBookActionPerformed

    private void searchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookActionPerformed
        jLabel1.setText("Search Books");
        br.setVisible(false);
        cp.setVisible(false);
        lob.setVisible(false);
        ep.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        ms.setVisible(false);
        
        r.setVisible(false);
        sb.setVisible(true);
        s.setVisible(false);
        ub.setVisible(false);
        dynamicPanel.setVisible(false);
        vb.setVisible(false);
        nb.setVisible(false);
    }//GEN-LAST:event_searchBookActionPerformed

    private void viewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookActionPerformed
        jLabel1.setText("Manage Borrowed Books");
        br.setVisible(false);
        cp.setVisible(false);
        ep.setVisible(false);
        lob.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(true);
        ms.setVisible(false);
        
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(false);
        ub.setVisible(false);
        dynamicPanel.setVisible(false);
        vb.setVisible(true);
        nb.setVisible(false);
    }//GEN-LAST:event_viewBookActionPerformed

    private void uploadBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBookActionPerformed
        jLabel1.setText("Upload Book");
        br.setVisible(false);
        cp.setVisible(false);
        lob.setVisible(false);
        ep.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        ms.setVisible(false);
        
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(false);
        vb.setVisible(false);
        ub.setVisible(true);
        dynamicPanel.setVisible(false);
        nb.setVisible(false);
    }//GEN-LAST:event_uploadBookActionPerformed

    private void softBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softBookActionPerformed
        jLabel1.setText("Soft Copies");
        br.setVisible(false);
        cp.setVisible(false);
        ep.setVisible(false);
        vb.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        ms.setVisible(false);
        
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(true);
        ub.setVisible(false);
        dynamicPanel.setVisible(false);
        nb.setVisible(false);
    }//GEN-LAST:event_softBookActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        jLabel1.setText("View Library Report");
        br.setVisible(false);
        cp.setVisible(false);
        lob.setVisible(false);
        ep.setVisible(false);
        vb.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        ms.setVisible(false);
        
        r.setVisible(true);
        sb.setVisible(false);
        s.setVisible(false);
        ub.setVisible(false);
        dynamicPanel.setVisible(false);

    }//GEN-LAST:event_reportActionPerformed

    private void bookRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRequestActionPerformed
        jLabel1.setText("Book Requests");
        br.setVisible(true);
        cp.setVisible(false);
        vb.setVisible(false);
        ep.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        ms.setVisible(false);
       
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(false);
        ub.setVisible(false);
        dynamicPanel.setVisible(false);
        nb.setVisible(false);
    }//GEN-LAST:event_bookRequestActionPerformed

    private void changePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassActionPerformed
        jLabel1.setText("Change User Password");
        br.setVisible(false);
        lob.setVisible(false);
        cp.setVisible(true);
        ep.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        vb.setVisible(false);
        ms.setVisible(false);
        
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(false);
        ub.setVisible(false);
        nb.setVisible(false);
    }//GEN-LAST:event_changePassActionPerformed

    private void editProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileActionPerformed
        jLabel1.setText("Edit your Profile");
        br.setVisible(false);
        cp.setVisible(false);
        ep.setVisible(true);
        vb.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        ms.setVisible(false);
        
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(false);
        ub.setVisible(false);
        dynamicPanel.setVisible(false);
        nb.setVisible(false);
    }//GEN-LAST:event_editProfileActionPerformed

    private void noticeBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticeBoardActionPerformed
        jLabel1.setText("Notice Board");
        br.setVisible(false);
        cp.setVisible(false);
        ep.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        lob.setVisible(false);
        ms.setVisible(false);
        vb.setVisible(false);
        nb.from.setText(uname.getText());
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(false);
        ub.setVisible(false);
        dynamicPanel.setVisible(false);
        nb.setVisible(true);
    }//GEN-LAST:event_noticeBoardActionPerformed

    private void booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksActionPerformed
        jLabel1.setText("List of Books");
        br.setVisible(false);
        lob.setVisible(true);
        cp.setVisible(false);
        ep.setVisible(false);
        vb.setVisible(false);
        mb.setVisible(false);
        mng.setVisible(false);
        ms.setVisible(false);
        r.setVisible(false);
        sb.setVisible(false);
        s.setVisible(false);
        ub.setVisible(false);
        dynamicPanel.setVisible(false);
        nb.setVisible(false);
    }//GEN-LAST:event_booksActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton bookRequest;
    private javax.swing.JButton books;
    private javax.swing.JButton changePass;
    private javax.swing.JLabel date;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JButton editProfile;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel logo;
    private javax.swing.JButton manageBook;
    private javax.swing.JButton manageStudent;
    private javax.swing.JLabel name;
    private javax.swing.JButton noticeBoard;
    private javax.swing.JButton report;
    private javax.swing.JButton searchBook;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton softBook;
    private javax.swing.JLabel time;
    public javax.swing.JLabel uname;
    private javax.swing.JButton uploadBook;
    private javax.swing.JButton viewBook;
    // End of variables declaration//GEN-END:variables
}
