
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Keith
 */
public class ManageBook extends javax.swing.JPanel {
    

    /**
     * Creates new form ManageBook
     */
    public ManageBook() {
        initComponents();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        addBook1 = new javax.swing.JPanel();
        ecl = new javax.swing.JTextField();
        ebookself = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        epublisher = new javax.swing.JTextField();
        eisbn = new javax.swing.JTextField();
        etitle = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        eauthor = new javax.swing.JTextField();
        ean1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        eedition = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ean = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addBook = new javax.swing.JPanel();
        cl = new javax.swing.JTextField();
        bookself = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        publisher = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        an = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edition = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 184, -1, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-2-icon.png"))); // NOI18N
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 140, 150));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-2-icon.png"))); // NOI18N
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 140, 150));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-2-icon.png"))); // NOI18N
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 140, 150));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-2-icon.png"))); // NOI18N
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 140, 150));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-2-icon.png"))); // NOI18N
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 140, 150));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-2-icon.png"))); // NOI18N
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 140, 150));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-2-icon.png"))); // NOI18N
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 140, 150));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-2-icon.png"))); // NOI18N
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, 150));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-2-icon.png"))); // NOI18N
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 150));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books-2-icon.png"))); // NOI18N
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 150));

        addBook1.setBackground(new java.awt.Color(255, 255, 255));
        addBook1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 4));
        addBook1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addBook1.add(ecl, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 111, 150, -1));
        addBook1.add(ebookself, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 149, 150, -1));

        jLabel13.setText("CL Accession:");
        addBook1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 114, -1, -1));
        addBook1.add(epublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 149, 150, -1));
        addBook1.add(eisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 73, 150, -1));
        addBook1.add(etitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 35, 150, -1));

        jLabel14.setText("Accession no:");
        addBook1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 38, -1, -1));

        jLabel15.setText("ISBN no:");
        addBook1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 76, -1, -1));

        jLabel16.setText("Bookself no:");
        addBook1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 152, -1, -1));
        addBook1.add(eauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 73, 150, -1));
        addBook1.add(ean1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 35, 150, -1));

        jLabel17.setText("Book Title:");
        addBook1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 38, -1, -1));

        jLabel18.setText("Author Name:");
        addBook1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 76, -1, -1));

        jLabel19.setText("Publisher:");
        addBook1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 152, -1, -1));

        jLabel20.setText("Edition:");
        addBook1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 114, -1, -1));
        addBook1.add(eedition, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 111, 150, -1));

        jButton2.setText("Edit");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        addBook1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 107, -1));

        add(addBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 630, 270));

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Edit Book");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Accession no:");

        ean.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eanKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel12)
                .addGap(120, 120, 120)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ean, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(ean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 630, 40));

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Book");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 230, -1));

        addBook.setBackground(new java.awt.Color(255, 255, 255));
        addBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 4));
        addBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addBook.add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 111, 150, -1));
        addBook.add(bookself, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 149, 150, -1));

        jLabel6.setText("CL Accession:");
        addBook.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 114, -1, -1));
        addBook.add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 149, 150, -1));
        addBook.add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 73, 150, -1));
        addBook.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 35, 150, -1));

        jLabel4.setText("Accession no:");
        addBook.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 38, -1, -1));

        jLabel5.setText("ISBN no:");
        addBook.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 76, -1, -1));

        jLabel10.setText("Bookself no:");
        addBook.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 152, -1, -1));
        addBook.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 73, 150, -1));
        addBook.add(an, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 35, 150, -1));

        jLabel7.setText("Book Title:");
        addBook.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 38, -1, -1));

        jLabel8.setText("Author Name:");
        addBook.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 76, -1, -1));

        jLabel11.setText("Publisher:");
        addBook.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 152, -1, -1));

        jLabel9.setText("Edition:");
        addBook.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 114, -1, -1));
        addBook.add(edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 111, 150, -1));

        jButton1.setText("Add Book");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        addBook.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 107, -1));

        add(addBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 630, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = Connectionz.getConnection();
            PreparedStatement pst = con.prepareStatement("UPDATE `books` SET `isbn`=?,`CL_accession`=?,`bookself`=?,`title`=?,`author`=?,`edition`=?,`publisher`=? WHERE accessionNO=?");
            pst.setString(1, an.getText());
            pst.setString(2, isbn.getText());
            pst.setString(3, cl.getText());
            pst.setString(4, bookself.getText());
            pst.setString(5, title.getText());
            pst.setString(6, author.getText());
            pst.setString(7, edition.getText());
            pst.setString(8, publisher.getText());
            pst.execute();

            JOptionPane.showMessageDialog(addBook1, "Book Updated successfully");
            JTextField temp = null;
            for(Component c:addBook1.getComponents()){
                if(c.getClass().toString().contains("javax.swing.JTextField")){
                    temp = (JTextField)c;
                    temp.setText(null);
                }
            }
        }catch(Exception e){JOptionPane.showMessageDialog(addBook1, e);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eanKeyReleased
        // TODO add your handling code here:
        try{
            Connection con = Connectionz.getConnection();
            PreparedStatement pst = con.prepareStatement("SELECT * FROM Books WHERE accessionNO=?");
            pst.setString(1, ean.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                ean1.setText(rs.getString("accessionNO"));
                eisbn.setText(rs.getString("isbn"));
                ecl.setText(rs.getString("CL_accession"));
                ebookself.setText(rs.getString("bookself"));
                etitle.setText(rs.getString("title"));
                eauthor.setText(rs.getString("author"));
                eedition.setText(rs.getString("edition"));
                epublisher.setText(rs.getString("publisher"));

                rs.close();
                pst.close();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(addBook, e);
        }
    }//GEN-LAST:event_eanKeyReleased

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        addBook.setVisible(false);

    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = Connectionz.getConnection();
            PreparedStatement pst = con.prepareStatement("INSERT INTO `Books`(`accessionNo`, `isbn`, `CL_accession`, `bookself`, `title`, `author`, `edition`, `publisher`) VALUES (?,?,?,?,?,?,?,?)");
            pst.setString(1, an.getText());
            pst.setString(2, isbn.getText());
            pst.setString(3, cl.getText());
            pst.setString(4, bookself.getText());
            pst.setString(5, title.getText());
            pst.setString(6, author.getText());
            pst.setString(7, edition.getText());
            pst.setString(8, publisher.getText());
            pst.execute();

            JOptionPane.showMessageDialog(addBook, "Book Added successfully");
            JTextField temp = null;
            for(Component c:addBook.getComponents()){
                if(c.getClass().toString().contains("javax.swing.JTextField")){
                    temp = (JTextField)c;
                    temp.setText(null);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(addBook, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBook;
    private javax.swing.JPanel addBook1;
    private javax.swing.JTextField an;
    private javax.swing.JTextField author;
    private javax.swing.JTextField bookself;
    private javax.swing.JTextField cl;
    private javax.swing.JTextField ean;
    private javax.swing.JTextField ean1;
    private javax.swing.JTextField eauthor;
    private javax.swing.JTextField ebookself;
    private javax.swing.JTextField ecl;
    private javax.swing.JTextField edition;
    private javax.swing.JTextField eedition;
    private javax.swing.JTextField eisbn;
    private javax.swing.JTextField epublisher;
    private javax.swing.JTextField etitle;
    private javax.swing.JTextField isbn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField publisher;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
